name: "Rust Setup"
description: "Setup the rust toolchain and cache"
inputs:
  GIT_CREDENTIALS:
    description: "Optional credentials to pass to git"
    required: false
  ADDITIONAL_KEY:
    description: "An optional additional key to pass to rust-cache"
    required: false
    default: ""

runs:
  using: composite
  steps:
    - run: sudo apt-get update && sudo apt-get install build-essential ca-certificates clang curl git libpq-dev libssl-dev pkg-config lsof lld --no-install-recommends --assume-yes
      shell: bash

    - uses: dsherret/rust-toolchain-file@v1

    # rust-cache action will cache ~/.cargo and ./target
    # https://github.com/Swatinem/rust-cache#cache-details
    - name: Run cargo cache
      if: !startsWith(github.ref, 'refs/pull/')
      uses: Swatinem/rust-cache@359a70e43a0bb8a13953b04a90f76428b4959bb6 # pin@v2.2.0
      with:
        key: ${{ inputs.ADDITIONAL_KEY }}

    - name: install protoc and related tools
      shell: bash
      run: scripts/dev_setup.sh -b -r -y -P -J -t

    - run: echo "/home/runner/.cargo/bin" | tee -a $GITHUB_PATH
      shell: bash

    - name: Setup git credentials
      if: inputs.GIT_CREDENTIALS != ''
      shell: bash
      run: |
        git config --global credential.helper store
        echo "${{ inputs.GIT_CREDENTIALS }}" > ~/.git-credentials

    # Display the rust toolchain version being installed
    - name: Setup rust toolchain
      shell: bash
      run: rustup show
